<template>
  <Card variant="default" class="mb-6">
    <div class="flex items-center gap-3 mb-6">
      <div class="w-10 h-10 bg-slate-100 rounded-lg flex items-center justify-center">
        <svg class="w-5 h-5 text-slate-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
      </div>
      <div>
        <h2 class="text-lg font-semibold text-slate-900">基本信息</h2>
        <p class="text-sm text-slate-500">设置机器人的名称和描述</p>
      </div>
    </div>
    <div class="space-y-4">
      <div>
        <div class="flex items-center justify-between mb-2">
          <label class="text-sm font-medium text-slate-700">机器人名称</label>
          <button
            type="button"
            @click="$emit('useAutoGeneratedName')"
            class="text-xs text-blue-600 hover:text-blue-700"
          >
            使用自动生成
          </button>
        </div>
        <Input
          :model-value="name"
          @update:model-value="$emit('update:name', $event)"
          placeholder="输入机器人名称"
          :error="error"
        />
      </div>
      <div>
        <div class="flex items-center justify-between mb-2">
          <label class="text-sm font-medium text-slate-700">描述</label>
          <button
            type="button"
            @click="$emit('useAutoGeneratedDescription')"
            class="text-xs text-blue-600 hover:text-blue-700"
          >
            使用自动生成
          </button>
        </div>
        <Input
          :model-value="description"
          @update:model-value="$emit('update:description', $event)"
          placeholder="输入机器人描述"
          type="textarea"
        />
      </div>
    </div>
  </Card>
</template>

<script setup>
import Card from '../../common/ui/Card.vue'
import Input from '../../common/ui/Input.vue'

defineProps({
  name: {
    type: String,
    default: ''
  },
  description: {
    type: String,
    default: ''
  },
  error: {
    type: String,
    default: ''
  }
})

defineEmits(['update:name', 'update:description', 'useAutoGeneratedName', 'useAutoGeneratedDescription'])
</script>

