<template>
  <aside class="w-80 flex-shrink-0">
    <div class="sticky top-24">
      <div class="bg-white rounded-lg border border-slate-200 shadow-sm overflow-hidden">
        <div class="bg-gradient-to-r from-slate-50 to-slate-100 px-4 py-3 border-b border-slate-200">
          <h3 class="text-slate-700 font-semibold flex items-center gap-2">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
            </svg>
            配置预览
          </h3>
        </div>

        <div class="p-4 space-y-4 max-h-[calc(100vh-280px)] overflow-y-auto">
          <!-- 机器人名称 -->
          <div>
            <div class="text-xs text-slate-500 mb-1">机器人名称</div>
            <div class="text-sm font-medium text-slate-900">
              {{ autoGeneratedName || '未命名信号机器人' }}
            </div>
          </div>

          <!-- 监控配置 -->
          <div class="border-t border-slate-200 pt-4">
            <div class="text-xs font-semibold text-slate-700 mb-3">监控配置</div>
            <div class="space-y-2">
              <div class="flex justify-between text-xs">
                <span class="text-slate-500">交易所</span>
                <span class="font-medium text-slate-900">
                  {{ selectedExchange?.label || '-' }}
                </span>
              </div>
              <div class="flex justify-between text-xs">
                <span class="text-slate-500">市场类型</span>
                <span class="font-medium text-slate-900">
                  <span :class="[
                    'inline-flex items-center px-1.5 py-0.5 rounded text-xs font-medium',
                    formData.market_type === 'spot' ? 'bg-green-100 text-green-700' : 'bg-blue-100 text-blue-700'
                  ]">
                    {{ formData.market_type === 'spot' ? '现货' : '合约' }}
                  </span>
                </span>
              </div>
              <div class="flex justify-between text-xs">
                <span class="text-slate-500">交易对</span>
                <span class="font-medium text-slate-900">
                  {{ selectedToken?.symbol ? `${selectedToken.symbol}/${formData.trading_pair || 'USDT'}` : '-' }}
                </span>
              </div>
              <div class="flex justify-between text-xs">
                <span class="text-slate-500">时间周期</span>
                <span class="font-medium text-slate-900">
                  {{ getTimeframeLabel(formData.timeframe) }}
                </span>
              </div>
            </div>
          </div>

          <!-- 信号类型 -->
          <div class="border-t border-slate-200 pt-4">
            <div class="text-xs font-semibold text-slate-700 mb-3">信号类型</div>
            <div class="flex items-center gap-2">
              <div v-if="formData.signal_type" class="inline-flex items-center px-2 py-1 bg-blue-100 text-blue-700 rounded text-xs font-medium">
                {{ getSignalTypeLabel(formData.signal_type) }}
              </div>
              <div v-else class="text-xs text-slate-400">未选择</div>
            </div>
          </div>

          <!-- 指标组合配置（仅在指标信号提醒时显示） -->
          <div v-if="formData.signal_type === 'indicator_alert' && selectedIndicators && selectedIndicators.length > 0" class="border-t border-slate-200 pt-4">
            <div class="text-xs font-semibold text-slate-700 mb-3 flex items-center justify-between">
              <span>指标组合</span>
              <span v-if="indicatorLogic" :class="[
                'px-2 py-0.5 rounded text-xs font-semibold',
                indicatorLogic === 'AND' ? 'bg-purple-100 text-purple-700' : 'bg-orange-100 text-orange-700'
              ]">
                {{ indicatorLogic === 'AND' ? '全部满足' : '任一满足' }}
              </span>
            </div>
            <div class="space-y-2">
              <div v-for="indicatorType in selectedIndicators" :key="indicatorType" class="bg-slate-50 rounded-lg p-2.5 border border-slate-200">
                <div class="flex items-center justify-between mb-1.5">
                  <div class="flex items-center gap-1.5">
                    <svg class="w-3.5 h-3.5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                    </svg>
                    <span class="text-xs font-semibold text-slate-900">{{ getIndicatorLabel(indicatorType) }}</span>
                  </div>
                  <span class="text-xs text-slate-500">权重: {{ getIndicatorWeight(indicatorType) }}</span>
                </div>
                <div class="text-xs text-slate-600 space-y-0.5">
                  <div v-for="(value, key) in getIndicatorParams(indicatorType)" :key="key" class="flex justify-between">
                    <span class="text-slate-500">{{ getParamLabel(key) }}:</span>
                    <span class="font-medium">{{ formatParamValue(key, value) }}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- 专业分析模式 -->
          <div class="border-t border-slate-200 pt-4">
            <div class="text-xs font-semibold text-slate-700 mb-3">分析模式</div>
            <div class="flex items-center justify-between">
              <span class="text-xs text-slate-500">专业分析</span>
              <div v-if="formData.use_advanced_analysis" class="inline-flex items-center px-2 py-1 bg-gradient-to-r from-purple-100 to-blue-100 text-purple-700 rounded text-xs font-semibold">
                <svg class="w-3 h-3 mr-1" fill="currentColor" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                </svg>
                已启用
              </div>
              <div v-else class="text-xs text-slate-400">未启用</div>
            </div>
          </div>

          <!-- 通知方式 -->
          <div class="border-t border-slate-200 pt-4">
            <div class="text-xs font-semibold text-slate-700 mb-3">通知方式</div>
            <div class="flex flex-wrap gap-2">
              <div v-if="formData.notify_email" class="inline-flex items-center px-2 py-1 bg-green-100 text-green-700 rounded text-xs">
                <svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path>
                </svg>
                邮件
              </div>
              <div v-if="formData.notify_app" class="inline-flex items-center px-2 py-1 bg-green-100 text-green-700 rounded text-xs">
                <svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z"></path>
                </svg>
                应用内
              </div>
              <div v-if="!formData.notify_email && !formData.notify_app" class="text-xs text-slate-400">
                未选择通知方式
              </div>
            </div>
          </div>

          <!-- 提醒配置 -->
          <div class="border-t border-slate-200 pt-4">
            <div class="text-xs font-semibold text-slate-700 mb-3">提醒配置</div>
            <div class="space-y-2.5">
              <div class="flex items-center justify-between text-xs">
                <div class="flex items-center gap-2">
                  <svg class="w-3.5 h-3.5 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                  </svg>
                  <span class="text-slate-600">提醒模式</span>
                </div>
                <span class="font-medium text-slate-900">
                  {{ getAlertModeLabel(alertConfig?.mode) }}
                </span>
              </div>
              <div v-if="alertConfig?.mode === 'condition_sustain'" class="flex items-center justify-between text-xs">
                <div class="flex items-center gap-2">
                  <svg class="w-3.5 h-3.5 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  <span class="text-slate-600">冷却时间</span>
                </div>
                <span class="font-medium text-slate-900">
                  {{ alertConfig?.cooldown_minutes || 30 }} 分钟
                </span>
              </div>
              <div class="flex items-center justify-between text-xs">
                <div class="flex items-center gap-2">
                  <svg class="w-3.5 h-3.5 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  <span class="text-slate-600">信号有效期</span>
                </div>
                <span class="font-medium text-slate-900">
                  {{ alertConfig?.signal_expiration_hours || 24 }} 小时
                </span>
              </div>
            </div>
          </div>

          <!-- 时间周期配置（仅在指标信号提醒时显示） -->
          <div v-if="formData.signal_type === 'indicator_alert'" class="border-t border-slate-200 pt-4">
            <div class="text-xs font-semibold text-slate-700 mb-3">时间周期</div>
            <div class="space-y-2">
              <div class="flex items-center justify-between text-xs">
                <span class="text-slate-600">主周期</span>
                <span class="font-medium text-slate-900">
                  {{ getTimeframeLabel(timeframesConfig?.primary || '1h') }}
                </span>
              </div>
              <div v-if="timeframesConfig?.confirm && timeframesConfig.confirm.length > 0" class="flex items-center justify-between text-xs">
                <span class="text-slate-600">确认周期</span>
                <span class="font-medium text-slate-900">
                  {{ timeframesConfig.confirm.map(tf => getTimeframeLabel(tf)).join(', ') }}
                </span>
              </div>
              <div v-if="timeframesConfig?.confirm && timeframesConfig.confirm.length > 0" class="flex items-center justify-between text-xs">
                <span class="text-slate-600">确认逻辑</span>
                <span class="font-medium text-slate-900">
                  {{ timeframesConfig.require_all_confirm ? '全部确认' : `至少${timeframesConfig.min_confirm_count}个` }}
                </span>
              </div>
            </div>
          </div>
        </div>

        <!-- 操作按钮 -->
        <div class="p-4 border-t border-slate-200 bg-slate-50 flex gap-3">
          <Button
            variant="primary"
            @click="$emit('submit')"
            :loading="submitting"
            :disabled="isBotRunning"
            class="flex-1"
          >
            {{ isEditMode ? '保存修改' : '创建机器人' }}
          </Button>
          <Button
            variant="secondary"
            @click="$emit('cancel')"
            class="flex-1"
          >
            取消
          </Button>
        </div>
      </div>
    </div>
  </aside>
</template>

<script setup>
import { computed } from 'vue'
import Button from '../../common/ui/Button.vue'

const props = defineProps({
  formData: Object,
  selectedExchange: Object,
  selectedExchangeAPI: Object,
  selectedToken: Object,
  alertConfig: Object,
  indicatorAlertType: String,
  rsiConfig: Object,
  macdConfig: Object,
  maCrossConfig: Object,
  atrConfig: Object,
  timeframesConfig: Object,
  isBotRunning: Boolean,
  submitting: Boolean,
  isEditMode: Boolean,
  // 新的多指标配置
  selectedIndicators: Array,
  indicatorLogic: String,
  indicatorsConfig: Object
})

defineEmits(['submit', 'cancel'])

const autoGeneratedName = computed(() => {
  if (props.formData.name) return props.formData.name
  const parts = []
  if (props.selectedToken?.symbol) parts.push(props.selectedToken.symbol)
  if (props.formData.trading_pair) parts.push(props.formData.trading_pair)

  // 如果是指标信号提醒
  if (props.formData.signal_type === 'indicator_alert') {
    // 优先使用多指标组合
    if (props.selectedIndicators && props.selectedIndicators.length > 0) {
      const indicatorLabels = {
        'rsi': 'RSI',
        'macd': 'MACD',
        'ma_crossover': 'MA交叉',
        'atr': 'ATR',
        'volume': '成交量'
      }

      // 如果是多个指标，显示组合
      if (props.selectedIndicators.length > 1) {
        const indicatorNames = props.selectedIndicators.map(type => indicatorLabels[type] || type)
        parts.push(`${indicatorNames.join('+')}组合`)
      } else {
        // 单个指标
        parts.push(indicatorLabels[props.selectedIndicators[0]] || '指标')
      }
    } else if (props.indicatorAlertType) {
      // 兼容旧的单指标格式
      const indicatorLabels = {
        'rsi': 'RSI',
        'macd': 'MACD',
        'ma_crossover': 'MA交叉',
        'atr': 'ATR'
      }
      parts.push(indicatorLabels[props.indicatorAlertType] || '指标信号提醒')
    } else {
      parts.push('指标信号提醒')
    }
  } else if (props.formData.signal_type) {
    parts.push(getSignalTypeLabel(props.formData.signal_type))
  }

  return parts.length > 0 ? parts.join(' ') + ' 信号' : '未命名信号机器人'
})

const getSignalTypeLabel = (type) => {
  // 简化：只保留 indicator_alert 类型
  const types = {
    'indicator_alert': '指标信号提醒',
    'rsi': 'RSI',
    'macd': 'MACD',
    'ma_crossover': 'MA交叉',
    'bollinger': '布林带',
    'kdj': 'KDJ'
  }
  return types[type] || '指标信号提醒'
}

const getTimeframeLabel = (timeframe) => {
  const timeframes = {
    '1m': '1分钟',
    '5m': '5分钟',
    '15m': '15分钟',
    '30m': '30分钟',
    '1h': '1小时',
    '4h': '4小时',
    '1d': '1天'
  }
  return timeframes[timeframe] || timeframe
}

const getAlertModeLabel = (mode) => {
  const modes = {
    'one_shot': '一次提醒',
    'condition_sustain': '条件维持提醒',
    'state_change': '状态变化提醒'
  }
  return modes[mode] || '-'
}

// 获取指标标签
const getIndicatorLabel = (type) => {
  const labels = {
    'rsi': 'RSI',
    'macd': 'MACD',
    'ma_crossover': 'MA交叉',
    'atr': 'ATR',
    'volume': '成交量',
    'bollinger': '布林带',
    'pattern': 'K线形态',
    'pivot': '支撑阻力位',
    'divergence': '背离',
    // 趋势过滤器
    'trend_bias': '趋势偏向',
    // 合约专用指标
    'funding_rate': '资金费率',
    'open_interest': '持仓量',
    'long_short_ratio': '多空比'
  }
  return labels[type] || type
}

// 获取指标权重
const getIndicatorWeight = (type) => {
  return props.indicatorsConfig?.[type]?.weight || 1
}

// 指标默认参数
const indicatorDefaults = {
  rsi: { period: 14, overbought: 70, oversold: 30 },
  macd: { fast: 12, slow: 26, signal: 9 },
  ma_crossover: { fast: 7, slow: 25 },
  atr: { period: 14, threshold: 2.0 },
  volume: { multiplier: 2.0, period: 20 },
  bollinger: { period: 20, std: 2, squeeze_threshold: 0.03 },
  pivot: { pivot_left: 3, pivot_right: 3 },
  pattern: { pinbar: true, engulfing: true, double_top: true, double_bottom: true },
  divergence: { divergence_lookback: 5, use_rsi: true, use_macd: true },
  // 趋势过滤器
  trend_bias: { fast_ma: 50, slow_ma: 200, bias_filter: true },
  // 合约专用指标
  funding_rate: { positive_extreme: 0.01, negative_extreme: -0.01, neutral_zone: [-0.002, 0.002] },
  open_interest: { oi_trend_period: 20, oi_increase_threshold: 5, oi_decrease_threshold: -5 },
  long_short_ratio: { extreme_long: 2.0, extreme_short: 0.5 }
}

// 获取指标参数（合并默认参数和用户配置）
const getIndicatorParams = (type) => {
  const defaults = indicatorDefaults[type] || {}
  const userParams = props.indicatorsConfig?.[type]?.params || {}
  return { ...defaults, ...userParams }
}

// 获取参数标签
const getParamLabel = (key) => {
  const labels = {
    // 通用参数
    'period': '周期',
    'threshold': '阈值',
    'multiplier': '倍数',

    // RSI 参数
    'overbought_threshold': '超买阈值',
    'oversold_threshold': '超卖阈值',
    'overbought': '超买阈值',
    'oversold': '超卖阈值',
    'reversal_strength': '反转强度',

    // MACD 参数
    'fast': '快线周期',
    'slow': '慢线周期',
    'signal': '信号线周期',
    'below_zero_cross': '零轴下方金叉',
    'golden_cross': '金叉信号',
    'green_shrink': '绿柱缩短',
    'signal_cross': '信号交叉',

    // MA 交叉参数
    'fast_period': '快线周期',
    'slow_period': '慢线周期',
    'ma_type': '均线类型',
    'cross_direction': '交叉方向',
    'break_fast_ma': '价格突破快线',

    // 成交量参数
    'volume_surge': '成交量激增',

    // ATR 参数
    'atr_surge': 'ATR激增',

    // 布林带参数
    'std': '标准差倍数',
    'std_dev': '标准差倍数',
    'squeeze_threshold': '挤压阈值',

    // K线形态参数
    'lookback': '回看周期',
    'pin_bar': '锤子线',
    'pinbar': '锤子线',
    'engulfing': '吞没形态',
    'double_top': '双顶',
    'double_bottom': '双底',

    // 支撑阻力位参数
    'pivot_left': '左侧K线',
    'pivot_right': '右侧K线',

    // 背离参数
    'divergence_lookback': '回看周期',
    'use_rsi': 'RSI背离',
    'use_macd': 'MACD背离',

    // 合约专用指标参数
    // 资金费率
    'positive_extreme': '极端多头阈值',
    'negative_extreme': '极端空头阈值',
    'neutral_zone': '中性区间',
    // 持仓量
    'oi_trend_period': '趋势周期',
    'oi_increase_threshold': '增仓阈值%',
    'oi_decrease_threshold': '减仓阈值%',
    // 多空比
    'extreme_long': '极端多头比例',
    'extreme_short': '极端空头比例',
    // 趋势偏向
    'fast_ma': '快线周期',
    'slow_ma': '慢线周期',
    'bias_filter': '启用过滤'
  }
  return labels[key] || key
}

// 格式化参数值
const formatParamValue = (key, value) => {
  // 布尔值转换
  if (typeof value === 'boolean' || value === 1 || value === 0 || value === '1' || value === '0') {
    const boolValue = value === true || value === 1 || value === '1'
    return boolValue ? '✓ 已启用' : '○ 未启用'
  }

  // 特殊字段的值转换
  if (key === 'signal_cross') {
    return value === 'bullish' ? '看涨' : value === 'bearish' ? '看跌' : value
  }

  if (key === 'ma_type') {
    return value === 'sma' ? 'SMA（简单）' : value === 'ema' ? 'EMA（指数）' : value
  }

  if (key === 'cross_direction') {
    return value === 'golden' ? '金叉' : value === 'death' ? '死叉' : value
  }

  return value
}
</script>
