<template>
  <aside class="w-80 flex-shrink-0">
    <div class="sticky top-24">
      <div class="bg-white rounded-lg border border-slate-200 shadow-sm overflow-hidden">
        <div class="bg-gradient-to-r from-slate-50 to-slate-100 px-4 py-3 border-b border-slate-200">
          <h3 class="text-slate-700 font-semibold flex items-center gap-2">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
            </svg>
            配置预览
          </h3>
        </div>

        <div class="p-4 space-y-4 max-h-[calc(100vh-280px)] overflow-y-auto">
          <!-- 机器人名称 -->
          <div>
            <div class="text-xs text-slate-500 mb-1">机器人名称</div>
            <div class="text-sm font-medium text-slate-900">
              {{ autoGeneratedName || '未命名信号机器人' }}
            </div>
          </div>

          <!-- 监控配置 -->
          <div class="border-t border-slate-200 pt-4">
            <div class="text-xs font-semibold text-slate-700 mb-3">监控配置</div>
            <div class="space-y-2">
              <div class="flex justify-between text-xs">
                <span class="text-slate-500">交易所</span>
                <span class="font-medium text-slate-900">
                  {{ selectedExchange?.label || '-' }}
                </span>
              </div>
              <div class="flex justify-between text-xs">
                <span class="text-slate-500">交易对</span>
                <span class="font-medium text-slate-900">
                  {{ selectedToken?.symbol ? `${selectedToken.symbol}/${formData.trading_pair || 'USDT'}` : '-' }}
                </span>
              </div>
              <div v-if="formData.signal_type !== 'price_alert'" class="flex justify-between text-xs">
                <span class="text-slate-500">时间周期</span>
                <span class="font-medium text-slate-900">
                  {{ getTimeframeLabel(formData.timeframe) }}
                </span>
              </div>
            </div>
          </div>

          <!-- 信号类型 -->
          <div class="border-t border-slate-200 pt-4">
            <div class="text-xs font-semibold text-slate-700 mb-3">信号类型</div>
            <div class="flex items-center gap-2">
              <div v-if="formData.signal_type" class="inline-flex items-center px-2 py-1 bg-blue-100 text-blue-700 rounded text-xs font-medium">
                {{ getSignalTypeLabel(formData.signal_type) }}
              </div>
              <div v-else class="text-xs text-slate-400">未选择</div>
            </div>
          </div>

          <!-- 专业分析模式 -->
          <div class="border-t border-slate-200 pt-4">
            <div class="text-xs font-semibold text-slate-700 mb-3">分析模式</div>
            <div class="flex items-center justify-between">
              <span class="text-xs text-slate-500">专业分析</span>
              <div v-if="formData.use_advanced_analysis" class="inline-flex items-center px-2 py-1 bg-gradient-to-r from-purple-100 to-blue-100 text-purple-700 rounded text-xs font-semibold">
                <svg class="w-3 h-3 mr-1" fill="currentColor" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                </svg>
                已启用
              </div>
              <div v-else class="text-xs text-slate-400">未启用</div>
            </div>
          </div>

          <!-- 通知方式 -->
          <div class="border-t border-slate-200 pt-4">
            <div class="text-xs font-semibold text-slate-700 mb-3">通知方式</div>
            <div class="flex flex-wrap gap-2">
              <div v-if="formData.notify_email" class="inline-flex items-center px-2 py-1 bg-green-100 text-green-700 rounded text-xs">
                <svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path>
                </svg>
                邮件
              </div>
              <div v-if="formData.notify_app" class="inline-flex items-center px-2 py-1 bg-green-100 text-green-700 rounded text-xs">
                <svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z"></path>
                </svg>
                应用内
              </div>
              <div v-if="!formData.notify_email && !formData.notify_app" class="text-xs text-slate-400">
                未选择通知方式
              </div>
            </div>
          </div>

          <!-- 提醒配置 -->
          <div class="border-t border-slate-200 pt-4">
            <div class="text-xs font-semibold text-slate-700 mb-3">提醒配置</div>
            <div class="space-y-2.5">
              <div class="flex items-center justify-between text-xs">
                <div class="flex items-center gap-2">
                  <svg class="w-3.5 h-3.5 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                  </svg>
                  <span class="text-slate-600">提醒模式</span>
                </div>
                <span class="font-medium text-slate-900">
                  {{ getAlertModeLabel(alertConfig?.mode) }}
                </span>
              </div>
              <div v-if="alertConfig?.mode === 'condition_sustain'" class="flex items-center justify-between text-xs">
                <div class="flex items-center gap-2">
                  <svg class="w-3.5 h-3.5 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  <span class="text-slate-600">冷却时间</span>
                </div>
                <span class="font-medium text-slate-900">
                  {{ alertConfig?.cooldown_minutes || 30 }} 分钟
                </span>
              </div>
              <div class="flex items-center justify-between text-xs">
                <div class="flex items-center gap-2">
                  <svg class="w-3.5 h-3.5 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  <span class="text-slate-600">信号有效期</span>
                </div>
                <span class="font-medium text-slate-900">
                  {{ alertConfig?.signal_expiration_hours || 24 }} 小时
                </span>
              </div>
            </div>
          </div>

          <!-- 指标配置（仅在指标信号提醒时显示） -->
          <div v-if="formData.signal_type === 'indicator_alert'" class="border-t border-slate-200 pt-4">
            <div class="text-xs font-semibold text-slate-700 mb-3">指标配置</div>
            <div class="space-y-2">
              <div class="flex items-center justify-between text-xs">
                <span class="text-slate-600">指标类型</span>
                <span class="font-medium text-slate-900">
                  {{ indicatorAlertType === 'rsi' ? 'RSI' : indicatorAlertType === 'macd' ? 'MACD' : indicatorAlertType === 'ma_crossover' ? 'MA交叉' : 'ATR' }}
                </span>
              </div>
              <div v-if="indicatorAlertType === 'rsi'" class="flex items-center justify-between text-xs">
                <span class="text-slate-600">周期/超买超卖</span>
                <span class="font-medium text-slate-900">
                  {{ rsiConfig?.period || 14 }}/{{ rsiConfig?.oversold || 30 }}-{{ rsiConfig?.overbought || 70 }}
                </span>
              </div>
              <div v-if="indicatorAlertType === 'macd'" class="flex items-center justify-between text-xs">
                <span class="text-slate-600">参数</span>
                <span class="font-medium text-slate-900">
                  {{ macdConfig?.fast || 12 }}/{{ macdConfig?.slow || 26 }}/{{ macdConfig?.signal || 9 }}
                </span>
              </div>
              <div v-if="indicatorAlertType === 'ma_crossover'" class="flex items-center justify-between text-xs">
                <span class="text-slate-600">快线/慢线周期</span>
                <span class="font-medium text-slate-900">
                  {{ maCrossConfig?.fast || 7 }}/{{ maCrossConfig?.slow || 25 }}
                </span>
              </div>
              <div v-if="indicatorAlertType === 'atr'" class="flex items-center justify-between text-xs">
                <span class="text-slate-600">周期/倍数</span>
                <span class="font-medium text-slate-900">
                  {{ atrConfig?.period || 14 }}/{{ atrConfig?.multiplier || 2.0 }}
                </span>
              </div>
            </div>
          </div>

          <!-- 时间周期配置（仅在指标信号提醒时显示） -->
          <div v-if="formData.signal_type === 'indicator_alert'" class="border-t border-slate-200 pt-4">
            <div class="text-xs font-semibold text-slate-700 mb-3">时间周期</div>
            <div class="space-y-2">
              <div class="flex items-center justify-between text-xs">
                <span class="text-slate-600">主周期</span>
                <span class="font-medium text-slate-900">
                  {{ getTimeframeLabel(timeframesConfig?.primary || '1h') }}
                </span>
              </div>
              <div v-if="timeframesConfig?.confirm && timeframesConfig.confirm.length > 0" class="flex items-center justify-between text-xs">
                <span class="text-slate-600">确认周期</span>
                <span class="font-medium text-slate-900">
                  {{ timeframesConfig.confirm.map(tf => getTimeframeLabel(tf)).join(', ') }}
                </span>
              </div>
              <div v-if="timeframesConfig?.confirm && timeframesConfig.confirm.length > 0" class="flex items-center justify-between text-xs">
                <span class="text-slate-600">确认逻辑</span>
                <span class="font-medium text-slate-900">
                  {{ timeframesConfig.require_all_confirm ? '全部确认' : `至少${timeframesConfig.min_confirm_count}个` }}
                </span>
              </div>
            </div>
          </div>
        </div>

        <!-- 操作按钮 -->
        <div class="p-4 border-t border-slate-200 bg-slate-50 flex gap-3">
          <Button
            variant="primary"
            @click="$emit('submit')"
            :loading="submitting"
            :disabled="isBotRunning"
            class="flex-1"
          >
            {{ isEditMode ? '保存修改' : '创建机器人' }}
          </Button>
          <Button
            variant="secondary"
            @click="$emit('cancel')"
            class="flex-1"
          >
            取消
          </Button>
        </div>
      </div>
    </div>
  </aside>
</template>

<script setup>
import { computed } from 'vue'
import Button from '../../common/ui/Button.vue'

const props = defineProps({
  formData: Object,
  selectedExchange: Object,
  selectedExchangeAPI: Object,
  selectedToken: Object,
  alertConfig: Object,
  indicatorAlertType: String,
  rsiConfig: Object,
  macdConfig: Object,
  maCrossConfig: Object,
  atrConfig: Object,
  timeframesConfig: Object,
  isBotRunning: Boolean,
  submitting: Boolean,
  isEditMode: Boolean
})

defineEmits(['submit', 'cancel'])

const autoGeneratedName = computed(() => {
  if (props.formData.name) return props.formData.name
  const parts = []
  if (props.selectedToken?.symbol) parts.push(props.selectedToken.symbol)
  if (props.formData.trading_pair) parts.push(props.formData.trading_pair)

  // 如果是指标信号提醒，使用具体的指标类型
  if (props.formData.signal_type === 'indicator_alert' && props.indicatorAlertType) {
    const indicatorLabels = {
      'rsi': 'RSI',
      'macd': 'MACD',
      'ma_crossover': 'MA交叉',
      'atr': 'ATR'
    }
    parts.push(indicatorLabels[props.indicatorAlertType] || '指标信号提醒')
  } else if (props.formData.signal_type) {
    parts.push(getSignalTypeLabel(props.formData.signal_type))
  }

  return parts.length > 0 ? parts.join(' ') + ' 信号' : '未命名信号机器人'
})

const getSignalTypeLabel = (type) => {
  const types = {
    'price_alert': '价格提醒',
    'indicator_alert': '指标信号提醒',
    'volatility': '波动性提醒',
    'volume': '成交量/持仓提醒',
    'rsi': 'RSI',
    'macd': 'MACD',
    'ma_crossover': 'MA交叉',
    'bollinger': '布林带',
    'kdj': 'KDJ'
  }
  return types[type] || type
}

const getTimeframeLabel = (timeframe) => {
  const timeframes = {
    '1m': '1分钟',
    '5m': '5分钟',
    '15m': '15分钟',
    '30m': '30分钟',
    '1h': '1小时',
    '4h': '4小时',
    '1d': '1天'
  }
  return timeframes[timeframe] || timeframe
}

const getAlertModeLabel = (mode) => {
  const modes = {
    'one_shot': '一次提醒',
    'condition_sustain': '条件维持提醒',
    'state_change': '状态变化提醒'
  }
  return modes[mode] || '-'
}
</script>
